language: csharp
mono: none
dotnet: 2.1.402
dist: trusty
solution: CleanMonads.sln
install:
 - dotnet restore CleanMonads.sln 
script:
 - dotnet build
 - dotnet test Monads.Tests
branches:
  only:
  - master
